change the configuration script.
git-svn-id: svn://svn.r-forge.r-project.org/svnroot/rcppbind@15 edb9625f-4e0d-4859-8d74-9fd3b1da38cb

diff --git a/pkg/configure b/pkg/configure
--- a/pkg/configure
+++ b/pkg/configure
@@ -2484,6 +2484,15 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
 
 
+: ${R_HOME=`R RHOME`}
+if test -z "${R_HOME}"; then
+  echo "could not determine R_HOME"
+  exit 1
+fi
+CC=`"${R_HOME}/bin/R" CMD config CC`
+CFLAGS=`"${R_HOME}/bin/R" CMD config CFLAGS`
+CPPFLAGS=`"${R_HOME}/bin/R" CMD config CPPFLAGS`
+
 mkdir -p inst/include
 mkdir -p inst/src
 cp include/* inst/include
